const a = {
    data: {
        pageBar: {
            dataCount: 141,
            pageIndex: 0,
            pageSize: 20,
        },
        searchEvaluationResults: [
            {
                applyAt: '2019-05-20 11:43:34',
                brandId: 1,
                brandName: 'NIKE',
                customerId: '1001',
                customerMarks: {
                    '3': '票贩子',
                    '4': '黄牛',
                    '5': '好人一生平安',
                    '7': '高危',
                },
                customerName: 'chengshanshan',
                evaluationCode: 'NQNIHQVG4JK0',
                evaluationId: 894,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2018/12/20/pktbfe5w10xwgzl3xwns7r1suusetxoi_',
                seriesId: 1,
                seriesName: 'ASC',
            },
            {
                applyAt: '2019-05-17 21:40:38',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: 'YJHTXPS9HN28',
                evaluationId: 823,
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 21:40:35',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: 'YFW8CCE0MTQ8',
                evaluationId: 811,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 21:40:34',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: 'YFOSDQ5TRLS0',
                evaluationId: 810,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 21:26:39',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '7T3T1QH9HM9S',
                evaluationId: 801,
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 21:25:13',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '524AIK07864G',
                evaluationId: 800,
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 21:07:53',
                brandId: 2,
                brandName: 'adidas',
                channel: '鉴定狮子军',
                customerId: '288534817199357952',
                customerMarks: {
                    '1': 'string',
                    '4': '黄牛',
                    '5': '好人一生平安',
                    '7': '高危',
                    '32': 'dsewewe',
                    '33': 'tt',
                },
                customerName: 'TODO',
                evaluationCode: '1BO9WOPODMZ28',
                evaluationId: 794,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2018/10/29/kzr1dh37mqypnyh7ggqbwp7bwu361si9_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 21:04:02',
                brandId: 2,
                brandName: 'adidas',
                channel: '鉴定狮子军',
                customerId: '288534817199357952',
                customerMarks: {
                    '1': 'string',
                    '4': '黄牛',
                    '5': '好人一生平安',
                    '7': '高危',
                    '32': 'dsewewe',
                    '33': 'tt',
                },
                customerName: 'TODO',
                evaluationCode: '1J132DC2D1F5S',
                evaluationId: 785,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2018/10/29/kzr1dh37mqypnyh7ggqbwp7bwu361si9_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 10:58:05',
                brandId: 11,
                brandName: 'Puma',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '1BQQ4HGANAEPS',
                evaluationId: 772,
                evaluationResult: {
                    code: '1',
                    message: '正在鉴定',
                },
                evaluationStatus: {
                    code: '1',
                    message: '未提交',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 160,
                seriesName: 'Puma Suede',
            },
            {
                applyAt: '2019-05-17 00:04:58',
                brandId: 3,
                brandName: 'AIR JORDAN',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '1CZ76KM12PGXS',
                evaluationId: 768,
                evaluationResult: {
                    code: '1',
                    message: '正在鉴定',
                },
                evaluationStatus: {
                    code: '1',
                    message: '未提交',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 3,
                seriesName: 'CSS',
            },
            {
                applyAt: '2019-05-17 00:04:56',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '1CWWOGSH9IEPS',
                evaluationId: 765,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-17 00:01:29',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '16BCSDPINOPVK',
                evaluationId: 762,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-16 23:38:53',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '7IZJT3SL3YTC',
                evaluationId: 761,
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-16 23:26:25',
                brandId: 12,
                brandName: 'Reebok',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: 'GAAT5W5CYJNK',
                evaluationId: 760,
                evaluationResult: {
                    code: '1',
                    message: '正在鉴定',
                },
                evaluationStatus: {
                    code: '1',
                    message: '未提交',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 183,
                seriesName: 'Print Smooth',
            },
            {
                applyAt: '2019-05-16 23:16:37',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: 'W3DEDTJ4KOAO',
                evaluationId: 750,
                evaluationResult: {
                    code: '1',
                    message: '正在鉴定',
                },
                evaluationStatus: {
                    code: '1',
                    message: '未提交',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-16 23:16:31',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: 'WADT70QUTRSW',
                evaluationId: 745,
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-16 23:10:07',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '1BG6QE4U4S8W0',
                evaluationId: 740,
                evaluationResult: {
                    code: '1',
                    message: '正在鉴定',
                },
                evaluationStatus: {
                    code: '1',
                    message: '未提交',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-16 23:09:59',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '1BPJA2PISWUTC',
                evaluationId: 733,
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-16 23:09:59',
                brandId: 2,
                brandName: 'adidas',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '1BQ1E1SRUD8U8',
                evaluationId: 731,
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
            {
                applyAt: '2019-05-16 23:09:52',
                brandId: 2,
                brandName: 'adidas',
                channel: '鉴定狮子军',
                customerId: '286060696804786176',
                customerMarks: {
                    '3': '票贩子',
                    '5': '好人一生平安',
                    '7': '高危',
                    '50': '任务',
                    '51': '111111当初说的才是大彻大悟',
                    '75': 'qwert',
                    '80': '嗷嗷',
                },
                customerName: 'TODO1',
                evaluationCode: '1BXJ84OG3P81S',
                evaluationId: 730,
                evaluationResult: {
                    code: '0',
                    message: '',
                },
                evaluationStatus: {
                    code: '0',
                    message: '',
                },
                mainImage: 'https://static.fashionipo.com/pic/2019/01/31/wwrc7bg13i39z4dmbdyoowyul5rmcrdp_',
                seriesId: 2,
                seriesName: 'ASDSC',
            },
        ],
    },
    header: {
        code: 2000,
        msg: 'SUCCEED',
    },
}
